url: https://ginogalotti.com
baseurl: /

# Site settings
title: Gino Galotti Muñoz
email: gino.galotti@gmail.com
description: "Gino Galotti's home page. Here you will find a summary of my cv, as well as other places you can find me."


# Team names, titles and social links
people:
- name: Gino Galotti
  pic: 1
  position: Quality Assistance
  social:
    - title: github
      url: https://github.com/GinoGalotti
    - title: linkedin
      url: https://www.linkedin.com/in/ginogalotti

- name: Gino Galotti
  pic: 2
  position: Improviser
  social:
    - title: github-alt
      url: https://improv.ginogalotti.com

- name: Gino Galotti
  pic: 3
  position: Writter
  social:
    - title: wordpress
      url: https://callmegino.wordpress.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/GinoGalotti
  - title: linkedin
    url: https://www.linkedin.com/in/ginogalotti

# Build settings
markdown: kramdown
permalink: pretty